### ISSUE TITLE
Django 2 support

### ISSUE THREAD

**Issue by jayvdb** [Genida/django-cerberus-ac#28]
I encountered import errors; the usual `urlresolvers`, etc.  Those should be easy to adapt to Django 2.

Are there larger incompatibilities lurking behind those?

**Comment by pawamoy** [comment]
I'm honestly not sure, as it's been a long time :slightly_smiling_face: 

Maybe you could try to update the url resolvers to see if something else breaks?

**Comment by jayvdb** [comment]
ok, will do.

**Comment by pawamoy** [comment]
Will likely not work on this project anymore.
